#navnet på workflowen 
name: Rull ut nettverk 

#ruller ut nettverks-stacken til dev automatisk med pucj
#ruller ut nettverks-stacken til test bar når det velges manuellt 
#ikke et eneste storage account-navn, en eneste parameterverdi eller passord i fila 
 

on: 
  push:
    branches: [main]  #automatisk ved push til main 
    paths: #dersom endringer treffer destinasjoner definert i paths
      - 'oving6/stacks/nettverk/**'
      - 'oving6/modules/network/**'
      - 'oving6/shared/backend.hcl'
      - '.github/workflows/deploy-nettverk.yml'
      - '.github/workflows/terraform-env.yml'

permissions:
  id-token: write #gir workflowen lov til å be GitHub om en OIDC-token
  #brukes av azure/login og terraform -provideren til å autentisere mot Azure uten passord/hemmelige nøkler 
  contents: read #lov til å lese innholdet i repoet 
 
concurrency:  
  group: nettverk
  cancel-in-progress: false  #pågående kjøring får fullføre i stedet for å bli avbrutt av en ny 
 
jobs:  
  dev:  #navnet på jobben 
    uses: ./.github/workflows/terraform-env.yml
    with: 
      miljo: dev
      plan_miljo: dev

    secrets: inherit


  test:
    needs: dev  #Gjør dette til en kjede 
    uses: ./.github/workflows/terraform-env.yml
    with:
      miljo: test
      plan_miljo: test

    secrets: inherit

  prod:
    needs: test
    uses: ./.github/workflows/terraform-env.yml
    with:
      miljo: prod
      plan_miljo: prod
    secrets: inherit 
    
    